services:
  postgres:
    image: postgres:16
    container_name: medall-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  bot:
    build: .
    container_name: medall-bot
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      INTRO_VIDEO_PATH: /app/cats_videos.mp4
    volumes:
      - ./cats_videos.mp4:/app/cats_videos.mp4:ro
    restart: unless-stopped

volumes:
  postgres_data:
